@startuml

Client      -> Articles : QUERY articles
Articles    -> Authors : QUERY authorById(id: Int)
Articles    <- Authors : Author
Client      <- Articles : [Article]

newpage

Client      -> Articles : QUERY articleById(id: Int)
Articles    -> Authors : QUERY authorById(id: Int)
Articles    <- Authors : Author
Client      <- Articles : Article

newpage

Client      -> Articles : MUTATION create(input: ArticleInput)
Client      <- Articles : Article

@enduml